# Generated by Django 5.1.7 on 2025-04-24 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_staff_alter_user_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='villege',
            new_name='villege_id',
        ),
    ]
