# Generated by Django 5.1.7 on 2025-04-24 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_villege_student_villege_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='villege_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.villege'),
        ),
    ]
