# Generated by Django 5.1.7 on 2025-04-24 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_student_villege_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='status_accont',
        ),
    ]
