# Generated by Django 5.1.7 on 2025-04-25 11:39

import apps.accounts.utils
import common.validator.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_status_accont'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to=apps.accounts.utils.profile_image_storage, validators=[common.validator.validators.validate_image_extension, common.validator.validators.validate_max_file_size]),
        ),
    ]
