# Generated by Django 5.1.7 on 2025-04-25 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customgroup_custompermission'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomGroup',
            new_name='Group',
        ),
        migrations.RenameModel(
            old_name='CustomPermission',
            new_name='Permission',
        ),
    ]
